### PR TITLE
custom permissions support

### PR DESCRIPTION
**Pull request by eriktelepovsky**
Custom permissions support thanks to mireq. I fixed one issue witch caused permissions with same value.

### CODE REVIEW

**Comment by jpic** [comment]
0. Oh god that app is still alive xD
1. You rock !
2. It's good for me, do you [want to make the release](http://docs.yourlabs.org) ? In that case what's your account name on PyPi ? I've given you permission on github repo in case you want to complete the release.

**Comment by luzfcb** [comment]
@jpic would be good to enable testing in travis, this will help other possible contributions

**Comment by eriktelepovsky** [comment]
Sure, no problem ;) My username on PyPi is **pragmaticmates.com**

**Comment by jpic** [comment]
Added you as maintainer on PyPi.

I don't see the 1.1.0 tag on GitHub, are you sure you pushed it ?

Please double check that you take all steps described in the release docs of docs.yourlabs.org

**Comment by eriktelepovsky** [comment]
I was fixing another issue with ``model_class._meta.verbose_name``, because ``PERMISSIONS_WIDGET_EXCLUDE_MODELS`` expects simple strings, but verbose_name use to be ``ugettext`` values. I created tag **1.1.1** instead.

**Pull request merged**
